"""AP70 model query helper — auto-generated by b2_eval_and_fit.py.

Model: AP70 = 0.630900 + 0.035046*log(s0/64) + 0.022255*log(s1/128) + 0.021243*log(s2/256)
Fitted on DAIR val 1789, FP16 TRT eval, stage_a pipeline.
Monotone non-decreasing in each stage width (b0, b1, b2 >= 0).
Fit MAE: 0.0094, Val MAE: 0.03466092135438181
"""
from __future__ import annotations
import math

def ap70(s0: int, s1: int, s2: int) -> float:
    """Predict AP70 for backbone widths [s0, s1, s2].

    Monotone: larger widths → higher AP70.
    Valid range: s0 in [16,64], s1 in [32,128], s2 in [64,256].
    Base widths: [64, 128, 256] → AP70 ≈ 0.6309.

    Args:
        s0: stage 0 num_filters (output channels of pyramid_backbone stage 0)
        s1: stage 1 num_filters
        s2: stage 2 num_filters

    Returns:
        Predicted AP70 (float)
    """
    a   = 0.630900
    b0  = 0.035046
    b1  = 0.022255
    b2  = 0.021243
    return a + b0 * math.log(s0 / 64.0) + b1 * math.log(s1 / 128.0) + b2 * math.log(s2 / 256.0)


if __name__ == "__main__":
    import sys
    configs = [
        ("base",     64, 128, 256),
        ("pruned25", 48,  96, 192),
        ("pruned50", 32,  64, 128),
        ("pruned75", 16,  32,  64),
        ("iso_s0",   48, 128, 256),
        ("iso_s1",   64,  96, 256),
        ("iso_s2",   64, 128, 192),
        ("mixed",    32,  96, 192),
        ("pad64",    64,  96, 192),
    ]
    print(f"{'tag':<12} {'s0,s1,s2':<20} {'AP70_pred':>12}")
    print("-" * 48)
    for tag, s0, s1, s2 in configs:
        pred = ap70(s0, s1, s2)
        print(f"{tag:<12} [{s0:3d},{s1:3d},{s2:3d}]             {pred:>12.4f}")
