"""TVM-only T1-Q micro-benchmarks for V2X-ViT attention fusion.

This script is meant to run on the H800 TVM environment:

  export PATH=/usr/local/cuda-12.2/bin:$PATH
  export LD_LIBRARY_PATH=$(cat /exdata/jichengzhi/tvm_nvlibs.path)
  CUDA_VISIBLE_DEVICES=6 /exdata/jichengzhi/tvm310/bin/python \\
      scripts/phase2/t1_attention_tvm_bench.py \\
      --out-json results/attention_axis_tvm_bench_v1.json

It intentionally avoids QDQ-ONNX quantization. INT8 evidence is generated by
direct TVM Relax matmul with int8 inputs and int32 accumulation.
"""

from __future__ import annotations

import argparse
import json
import time
import traceback
from pathlib import Path
from typing import Any

import numpy as np


def _round(value: Any, digits: int = 4) -> float | None:
    try:
        return round(float(value), digits)
    except (TypeError, ValueError):
        return None


def _latency_entry(status: str, p50_us: float | None = None, **extra) -> dict[str, Any]:
    entry = {"status": status}
    if p50_us is not None:
        entry["p50_ms"] = _round(p50_us / 1000.0, 6)
        entry["p50_us"] = _round(p50_us, 3)
    entry.update(extra)
    return entry


def _time_vm(vm, args, dev, number: int, repeat: int) -> dict[str, float]:
    vm["main"](*args)
    dev.sync()
    timer = vm.time_evaluator("main", dev, number=number, repeat=repeat)
    result = timer(*args)
    values_us = [x * 1e6 for x in result.results]
    return {
        "mean_us": float(np.mean(values_us)),
        "p50_us": float(np.percentile(values_us, 50)),
        "min_us": float(np.min(values_us)),
        "p95_us": float(np.percentile(values_us, 95)),
    }


def make_mswin_bwa_shape_plan(
    batch: int,
    agents: int,
    h: int,
    w: int,
    channels: int,
    heads: int,
    dim_head: int,
    window_size: int,
    prune_rate_pct: int,
) -> dict[str, Any]:
    if h % window_size != 0 or w % window_size != 0:
        raise ValueError("h and w must be divisible by window_size")
    inner_dim = heads * dim_head
    new_h = h // window_size
    new_w = w // window_size
    window_tokens = window_size * window_size
    flat_m = batch * agents * h * w
    return {
        "input_shape": [batch, agents, h, w, channels],
        "batch": batch,
        "agents": agents,
        "h": h,
        "w": w,
        "channels": channels,
        "heads": heads,
        "dim_head": dim_head,
        "inner_dim": inner_dim,
        "window_size": window_size,
        "new_h": new_h,
        "new_w": new_w,
        "window_tokens": window_tokens,
        "window_batches": batch * agents * heads * new_h * new_w,
        "qkv_shape_mkn": [flat_m, channels, inner_dim],
        "out_shape_mkn": [flat_m, inner_dim, channels],
        "prune_rate_pct": prune_rate_pct,
    }


def make_hmsa_shape_plan(
    batch: int,
    agents: int,
    h: int,
    w: int,
    channels: int,
    heads: int,
    dim_head: int,
    num_types: int,
    num_relations: int,
    prune_rate_pct: int,
) -> dict[str, Any]:
    if agents != 2:
        raise ValueError("minimal HMSA target currently fixes agents=2")
    if num_types != 2 or num_relations != 4:
        raise ValueError("minimal HMSA target expects num_types=2 and num_relations=4")
    inner_dim = heads * dim_head
    spatial_tokens = batch * h * w
    flat_agent_tokens = spatial_tokens * agents
    return {
        "input_shape": [batch, agents, h, w, channels],
        "batch": batch,
        "agents": agents,
        "h": h,
        "w": w,
        "channels": channels,
        "heads": heads,
        "dim_head": dim_head,
        "inner_dim": inner_dim,
        "num_types": num_types,
        "num_relations": num_relations,
        "spatial_tokens": spatial_tokens,
        "flat_agent_tokens": flat_agent_tokens,
        "relation_att_shape": [num_relations, heads, dim_head, dim_head],
        "relation_msg_shape": [num_relations, heads, dim_head, dim_head],
        "relation_pair_order": ["0->0", "0->1", "1->0", "1->1"],
        "qkv_shape_mkn": [flat_agent_tokens, channels, inner_dim],
        "out_shape_mkn": [flat_agent_tokens, inner_dim, channels],
        "core_tensor_shape": [heads, spatial_tokens, dim_head],
        "attention_map_shape": [batch, heads, h, w, agents, agents],
        "prune_rate_pct": prune_rate_pct,
        "caveat": (
            "Minimal target fixes B=1,L=2 and explicit relation pair order; "
            "dynamic type dispatch is not covered until a later HMSA TVM pass."
        ),
    }


def make_hmsa_static_2agent_param_plan(plan: dict[str, Any]) -> dict[str, Any]:
    """Describe the static HMSA TVM target used before dynamic type lowering.

    The real PyTorch module chooses q/k/v/a linears from ``types`` at runtime.
    This target fixes the common DAIR two-agent type order [0, 1], so the TVM
    function can include real q/k/v and output projections without dynamic
    ModuleList dispatch yet.
    """
    b, l, h, w, c = plan["input_shape"]
    if b != 1 or l != 2:
        raise ValueError("static HMSA target currently requires B=1,L=2")
    inner = plan["inner_dim"]
    spatial = plan["spatial_tokens"]
    qkv_shapes = {
        "q_type0": [c, inner],
        "k_type0": [c, inner],
        "v_type0": [c, inner],
        "q_type1": [c, inner],
        "k_type1": [c, inner],
        "v_type1": [c, inner],
    }
    return {
        "scope": "hmsa_static_2agent_qkv_relation_out",
        "static_type_order": [0, 1],
        "x_agent_shape": [spatial, c],
        "qkv_weight_shapes": qkv_shapes,
        "relation_att_pair_order": plan["relation_pair_order"],
        "relation_att_shape": plan["relation_att_shape"],
        "relation_msg_shape": plan["relation_msg_shape"],
        "out_weight_shapes": {
            "type0": [inner, c],
            "type1": [inner, c],
        },
        "output_shape": [b, l, h, w, c],
        "covers_qkv_projection": True,
        "covers_output_projection": True,
        "covers_dynamic_type_dispatch": False,
        "caveat": "Static type order [0,1]; dynamic prior_encoding types dispatch remains separate work.",
    }


def _minimal_target_text(plan: dict[str, Any]) -> str:
    b, l, h, w, c = plan["input_shape"]
    rel = plan["relation_att_shape"]
    return (
        f"B={b},L={l},H={h},W={w},C={c},heads={plan['heads']},"
        f"dim_head={plan['dim_head']},inner_dim={plan['inner_dim']},"
        f"relation_att/msg=({rel[0]},{rel[1]},{rel[2]},{rel[3]})"
    )


def make_hmsa_not_implemented_entry(plan: dict[str, Any], precision: str) -> dict[str, Any]:
    return {
        "status": "BLOCKED",
        "precision": precision,
        "stage": "NOT_IMPLEMENTED",
        "op": "HGTCavAttention relation einsum and per-type q/k/v/a dispatch",
        "minimal_target": _minimal_target_text(plan),
        "reason": (
            "No successful TVM Relax/TIR lowering has been recorded for HMSA relation "
            "attention. Implement build_relax_hmsa_relation_core_* or attach a concrete "
            "failing command/log/trace."
        ),
    }


def make_tvm_blocked_entry(
    precision: str,
    stage: str,
    op: str,
    exc: Exception,
    traceback_text: str,
) -> dict[str, Any]:
    return {
        "status": "BLOCKED",
        "precision": precision,
        "stage": stage,
        "op": op,
        "error": f"{type(exc).__name__}: {exc}",
        "traceback": traceback_text[-4000:],
    }


def build_relax_matmul(dtype: str, m: int, k: int, n: int, out_dtype: str | None):
    import tvm
    from tvm import relax

    bb = relax.BlockBuilder()
    x = relax.Var("x", relax.TensorStructInfo((m, k), dtype))
    w = relax.Var("w", relax.TensorStructInfo((k, n), dtype))
    with bb.function("main", [x, w]):
        with bb.dataflow():
            y = bb.emit(relax.op.matmul(x, w, out_dtype=out_dtype) if out_dtype else relax.op.matmul(x, w))
            gv = bb.emit_output(y)
        bb.emit_func_output(gv)
    return bb.finalize()


def compile_relax_module(mod, target):
    import tvm
    from tvm import relax
    import tvm.s_tir.dlight as dl

    seq = tvm.transform.Sequential([
        relax.transform.LegalizeOps(),
        relax.transform.AnnotateTIROpPattern(),
        relax.transform.FuseOps(),
        relax.transform.FuseTIR(),
    ])
    with target, tvm.transform.PassContext(opt_level=3):
        mod = seq(mod)
        mod = dl.ApplyDefaultSchedule(
            dl.gpu.Matmul(),
            dl.gpu.GEMV(),
            dl.gpu.Reduction(),
            dl.gpu.GeneralReduction(),
            dl.gpu.Fallback(),
        )(mod)
        return tvm.compile(mod, target=target)


def _reshape_windows(expr, plan: dict[str, Any]):
    from tvm import relax

    b, l, h, w, heads, dim_head = (
        plan["batch"],
        plan["agents"],
        plan["h"],
        plan["w"],
        plan["heads"],
        plan["dim_head"],
    )
    ws = plan["window_size"]
    new_h = plan["new_h"]
    new_w = plan["new_w"]
    expr = relax.op.reshape(expr, (b, l, new_h, ws, new_w, ws, heads, dim_head))
    expr = relax.op.permute_dims(expr, axes=[0, 1, 6, 2, 4, 3, 5, 7])
    return relax.op.reshape(expr, (plan["window_batches"], plan["window_tokens"], dim_head))


def _unshape_windows(expr, plan: dict[str, Any]):
    from tvm import relax

    b, l, heads, dim_head = plan["batch"], plan["agents"], plan["heads"], plan["dim_head"]
    ws, new_h, new_w = plan["window_size"], plan["new_h"], plan["new_w"]
    expr = relax.op.reshape(expr, (b, l, heads, new_h, new_w, ws, ws, dim_head))
    expr = relax.op.permute_dims(expr, axes=[0, 1, 3, 5, 4, 6, 2, 7])
    return relax.op.reshape(expr, (b * l * plan["h"] * plan["w"], plan["inner_dim"]))


def build_relax_mswin_bwa_fp16(plan: dict[str, Any]):
    from tvm import relax

    b, l, h, w, c = plan["input_shape"]
    inner = plan["inner_dim"]
    tokens = plan["window_tokens"]
    bb = relax.BlockBuilder()
    x = relax.Var("x", relax.TensorStructInfo((b, l, h, w, c), "float16"))
    wq = relax.Var("wq", relax.TensorStructInfo((c, inner), "float16"))
    wk = relax.Var("wk", relax.TensorStructInfo((c, inner), "float16"))
    wv = relax.Var("wv", relax.TensorStructInfo((c, inner), "float16"))
    wo = relax.Var("wo", relax.TensorStructInfo((inner, c), "float16"))
    pos = relax.Var("pos", relax.TensorStructInfo((tokens, tokens), "float16"))
    with bb.function("main", [x, wq, wk, wv, wo, pos]):
        with bb.dataflow():
            x2 = bb.emit(relax.op.reshape(x, (b * l * h * w, c)))
            q = bb.emit(relax.op.matmul(x2, wq))
            k = bb.emit(relax.op.matmul(x2, wk))
            v = bb.emit(relax.op.matmul(x2, wv))
            q_w = bb.emit(_reshape_windows(q, plan))
            k_w = bb.emit(_reshape_windows(k, plan))
            v_w = bb.emit(_reshape_windows(v, plan))
            k_t = bb.emit(relax.op.permute_dims(k_w, axes=[0, 2, 1]))
            dots = bb.emit(relax.op.matmul(q_w, k_t))
            pos_b = bb.emit(relax.op.reshape(pos, (1, tokens, tokens)))
            dots = bb.emit(relax.op.add(dots, pos_b))
            attn = bb.emit(relax.op.nn.softmax(dots, axis=-1))
            out = bb.emit(relax.op.matmul(attn, v_w))
            out2 = bb.emit(_unshape_windows(out, plan))
            y = bb.emit(relax.op.matmul(out2, wo))
            y = bb.emit(relax.op.reshape(y, (b, l, h, w, c)))
            gv = bb.emit_output(y)
        bb.emit_func_output(gv)
    return bb.finalize()


def build_relax_mswin_bwa_mixed_int8(plan: dict[str, Any]):
    from tvm import relax

    b, l, h, w, c = plan["input_shape"]
    inner = plan["inner_dim"]
    tokens = plan["window_tokens"]
    bb = relax.BlockBuilder()
    x = relax.Var("x", relax.TensorStructInfo((b, l, h, w, c), "int8"))
    wq = relax.Var("wq", relax.TensorStructInfo((c, inner), "int8"))
    wk = relax.Var("wk", relax.TensorStructInfo((c, inner), "int8"))
    wv = relax.Var("wv", relax.TensorStructInfo((c, inner), "int8"))
    wo = relax.Var("wo", relax.TensorStructInfo((inner, c), "int8"))
    pos = relax.Var("pos", relax.TensorStructInfo((tokens, tokens), "float16"))
    with bb.function("main", [x, wq, wk, wv, wo, pos]):
        with bb.dataflow():
            x2 = bb.emit(relax.op.reshape(x, (b * l * h * w, c)))
            q = bb.emit(relax.op.matmul(x2, wq, out_dtype="int32"))
            k = bb.emit(relax.op.matmul(x2, wk, out_dtype="int32"))
            v = bb.emit(relax.op.matmul(x2, wv, out_dtype="int32"))
            q = bb.emit(relax.op.astype(q, "int8"))
            k = bb.emit(relax.op.astype(k, "int8"))
            v = bb.emit(relax.op.astype(v, "int8"))
            q_w = bb.emit(_reshape_windows(q, plan))
            k_w = bb.emit(_reshape_windows(k, plan))
            v_w = bb.emit(_reshape_windows(v, plan))
            k_t = bb.emit(relax.op.permute_dims(k_w, axes=[0, 2, 1]))
            dots = bb.emit(relax.op.matmul(q_w, k_t, out_dtype="int32"))
            dots = bb.emit(relax.op.astype(dots, "float16"))
            pos_b = bb.emit(relax.op.reshape(pos, (1, tokens, tokens)))
            dots = bb.emit(relax.op.add(dots, pos_b))
            attn = bb.emit(relax.op.nn.softmax(dots, axis=-1))
            attn = bb.emit(relax.op.astype(attn, "int8"))
            out = bb.emit(relax.op.matmul(attn, v_w, out_dtype="int32"))
            out = bb.emit(relax.op.astype(out, "int8"))
            out2 = bb.emit(_unshape_windows(out, plan))
            y = bb.emit(relax.op.matmul(out2, wo, out_dtype="int32"))
            y = bb.emit(relax.op.astype(y, "float16"))
            y = bb.emit(relax.op.reshape(y, (b, l, h, w, c)))
            gv = bb.emit_output(y)
        bb.emit_func_output(gv)
    return bb.finalize()


def _hmsa_pair_score(bb, q, rel_att, k, dim_head: int):
    from tvm import relax

    q_rel = bb.emit(relax.op.matmul(q, rel_att))
    prod = bb.emit(relax.op.multiply(q_rel, k))
    score = bb.emit(relax.op.sum(prod, axis=2))
    scale = relax.const(dim_head ** -0.5, "float16")
    return bb.emit(relax.op.multiply(score, scale))


def _hmsa_pair_score_mixed(bb, q, rel_att, k, dim_head: int):
    from tvm import relax

    q_rel = bb.emit(relax.op.matmul(q, rel_att, out_dtype="int32"))
    q_rel = bb.emit(relax.op.astype(q_rel, "float16"))
    k_fp = bb.emit(relax.op.astype(k, "float16"))
    prod = bb.emit(relax.op.multiply(q_rel, k_fp))
    score = bb.emit(relax.op.sum(prod, axis=2))
    scale = relax.const(dim_head ** -0.5, "float16")
    return bb.emit(relax.op.multiply(score, scale))


def _softmax_two(bb, score0, score1):
    from tvm import relax

    exp0 = bb.emit(relax.op.exp(score0))
    exp1 = bb.emit(relax.op.exp(score1))
    denom = bb.emit(relax.op.add(exp0, exp1))
    return bb.emit(relax.op.divide(exp0, denom)), bb.emit(relax.op.divide(exp1, denom))


def _hmsa_message(bb, v, rel_msg):
    from tvm import relax

    return bb.emit(relax.op.matmul(v, rel_msg))


def _hmsa_message_mixed(bb, v, rel_msg):
    from tvm import relax

    msg = bb.emit(relax.op.matmul(v, rel_msg, out_dtype="int32"))
    return bb.emit(relax.op.astype(msg, "float16"))


def _weighted_pair_sum(bb, w0, msg0, w1, msg1, heads: int, spatial_tokens: int):
    from tvm import relax

    w0 = bb.emit(relax.op.reshape(w0, (heads, spatial_tokens, 1)))
    w1 = bb.emit(relax.op.reshape(w1, (heads, spatial_tokens, 1)))
    part0 = bb.emit(relax.op.multiply(w0, msg0))
    part1 = bb.emit(relax.op.multiply(w1, msg1))
    return bb.emit(relax.op.add(part0, part1))


def _hmsa_project_out(bb, out, wo, plan: dict[str, Any]):
    from tvm import relax

    out = bb.emit(relax.op.permute_dims(out, axes=[1, 0, 2]))
    out = bb.emit(relax.op.reshape(out, (plan["spatial_tokens"], plan["inner_dim"])))
    return bb.emit(relax.op.matmul(out, wo))


def _hmsa_project_out_mixed(bb, out, wo, plan: dict[str, Any]):
    from tvm import relax

    out = bb.emit(relax.op.permute_dims(out, axes=[1, 0, 2]))
    out = bb.emit(relax.op.reshape(out, (plan["spatial_tokens"], plan["inner_dim"])))
    out = bb.emit(relax.op.astype(out, "int8"))
    y = bb.emit(relax.op.matmul(out, wo, out_dtype="int32"))
    return bb.emit(relax.op.astype(y, "float16"))


def _hmsa_project_qkv(bb, x, wq, wk, wv, plan: dict[str, Any]):
    from tvm import relax

    heads, dim_head = plan["heads"], plan["dim_head"]
    spatial = plan["spatial_tokens"]
    q = bb.emit(relax.op.matmul(x, wq))
    k = bb.emit(relax.op.matmul(x, wk))
    v = bb.emit(relax.op.matmul(x, wv))
    q = bb.emit(relax.op.reshape(q, (spatial, heads, dim_head)))
    k = bb.emit(relax.op.reshape(k, (spatial, heads, dim_head)))
    v = bb.emit(relax.op.reshape(v, (spatial, heads, dim_head)))
    q = bb.emit(relax.op.permute_dims(q, axes=[1, 0, 2]))
    k = bb.emit(relax.op.permute_dims(k, axes=[1, 0, 2]))
    v = bb.emit(relax.op.permute_dims(v, axes=[1, 0, 2]))
    return q, k, v


def _hmsa_project_qkv_mixed(bb, x, wq, wk, wv, plan: dict[str, Any]):
    from tvm import relax

    heads, dim_head = plan["heads"], plan["dim_head"]
    spatial = plan["spatial_tokens"]
    q = bb.emit(relax.op.matmul(x, wq, out_dtype="int32"))
    k = bb.emit(relax.op.matmul(x, wk, out_dtype="int32"))
    v = bb.emit(relax.op.matmul(x, wv, out_dtype="int32"))
    q = bb.emit(relax.op.astype(q, "int8"))
    k = bb.emit(relax.op.astype(k, "int8"))
    v = bb.emit(relax.op.astype(v, "int8"))
    q = bb.emit(relax.op.reshape(q, (spatial, heads, dim_head)))
    k = bb.emit(relax.op.reshape(k, (spatial, heads, dim_head)))
    v = bb.emit(relax.op.reshape(v, (spatial, heads, dim_head)))
    q = bb.emit(relax.op.permute_dims(q, axes=[1, 0, 2]))
    k = bb.emit(relax.op.permute_dims(k, axes=[1, 0, 2]))
    v = bb.emit(relax.op.permute_dims(v, axes=[1, 0, 2]))
    return q, k, v


def _hmsa_emit_relation_body(bb, q0, k0, v0, q1, k1, v1, rels, outs, plan: dict[str, Any], mixed: bool):
    from tvm import relax

    heads = plan["heads"]
    spatial = plan["spatial_tokens"]
    dim_head = plan["dim_head"]
    r00a, r01a, r10a, r11a, r00m, r01m, r10m, r11m = rels
    wo0, wo1 = outs
    pair_score = _hmsa_pair_score_mixed if mixed else _hmsa_pair_score
    message = _hmsa_message_mixed if mixed else _hmsa_message
    project = _hmsa_project_out_mixed if mixed else _hmsa_project_out

    s00 = pair_score(bb, q0, r00a, k0, dim_head)
    s01 = pair_score(bb, q0, r01a, k1, dim_head)
    s10 = pair_score(bb, q1, r10a, k0, dim_head)
    s11 = pair_score(bb, q1, r11a, k1, dim_head)
    w00, w01 = _softmax_two(bb, s00, s01)
    w10, w11 = _softmax_two(bb, s10, s11)
    msg00 = message(bb, v0, r00m)
    msg01 = message(bb, v1, r01m)
    msg10 = message(bb, v0, r10m)
    msg11 = message(bb, v1, r11m)
    out0 = _weighted_pair_sum(bb, w00, msg00, w01, msg01, heads, spatial)
    out1 = _weighted_pair_sum(bb, w10, msg10, w11, msg11, heads, spatial)
    y0 = project(bb, out0, wo0, plan)
    y1 = project(bb, out1, wo1, plan)
    y = bb.emit(relax.op.concat([y0, y1], axis=0))
    b, l, h, w, c = plan["input_shape"]
    return bb.emit(relax.op.reshape(y, (b, l, h, w, c)))


def build_relax_hmsa_relation_core_fp16(plan: dict[str, Any]):
    from tvm import relax

    b, l, h, w, c = plan["input_shape"]
    if b != 1 or l != 2:
        raise ValueError("HMSA minimal relation core currently requires B=1,L=2")
    heads, dim_head, inner = plan["heads"], plan["dim_head"], plan["inner_dim"]
    spatial = plan["spatial_tokens"]
    bb = relax.BlockBuilder()
    q0 = relax.Var("q0", relax.TensorStructInfo((heads, spatial, dim_head), "float16"))
    k0 = relax.Var("k0", relax.TensorStructInfo((heads, spatial, dim_head), "float16"))
    v0 = relax.Var("v0", relax.TensorStructInfo((heads, spatial, dim_head), "float16"))
    q1 = relax.Var("q1", relax.TensorStructInfo((heads, spatial, dim_head), "float16"))
    k1 = relax.Var("k1", relax.TensorStructInfo((heads, spatial, dim_head), "float16"))
    v1 = relax.Var("v1", relax.TensorStructInfo((heads, spatial, dim_head), "float16"))
    r00a = relax.Var("r00a", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r01a = relax.Var("r01a", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r10a = relax.Var("r10a", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r11a = relax.Var("r11a", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r00m = relax.Var("r00m", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r01m = relax.Var("r01m", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r10m = relax.Var("r10m", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r11m = relax.Var("r11m", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    wo0 = relax.Var("wo0", relax.TensorStructInfo((inner, c), "float16"))
    wo1 = relax.Var("wo1", relax.TensorStructInfo((inner, c), "float16"))
    params = [q0, k0, v0, q1, k1, v1, r00a, r01a, r10a, r11a, r00m, r01m, r10m, r11m, wo0, wo1]
    with bb.function("main", params):
        with bb.dataflow():
            s00 = _hmsa_pair_score(bb, q0, r00a, k0, dim_head)
            s01 = _hmsa_pair_score(bb, q0, r01a, k1, dim_head)
            s10 = _hmsa_pair_score(bb, q1, r10a, k0, dim_head)
            s11 = _hmsa_pair_score(bb, q1, r11a, k1, dim_head)
            w00, w01 = _softmax_two(bb, s00, s01)
            w10, w11 = _softmax_two(bb, s10, s11)
            msg00 = _hmsa_message(bb, v0, r00m)
            msg01 = _hmsa_message(bb, v1, r01m)
            msg10 = _hmsa_message(bb, v0, r10m)
            msg11 = _hmsa_message(bb, v1, r11m)
            out0 = _weighted_pair_sum(bb, w00, msg00, w01, msg01, heads, spatial)
            out1 = _weighted_pair_sum(bb, w10, msg10, w11, msg11, heads, spatial)
            y0 = _hmsa_project_out(bb, out0, wo0, plan)
            y1 = _hmsa_project_out(bb, out1, wo1, plan)
            y = bb.emit(relax.op.concat([y0, y1], axis=0))
            y = bb.emit(relax.op.reshape(y, (b, l, h, w, c)))
            gv = bb.emit_output(y)
        bb.emit_func_output(gv)
    return bb.finalize()


def build_relax_hmsa_relation_core_mixed_int8(plan: dict[str, Any]):
    from tvm import relax

    b, l, h, w, c = plan["input_shape"]
    if b != 1 or l != 2:
        raise ValueError("HMSA minimal relation core currently requires B=1,L=2")
    heads, dim_head, inner = plan["heads"], plan["dim_head"], plan["inner_dim"]
    spatial = plan["spatial_tokens"]
    bb = relax.BlockBuilder()
    q0 = relax.Var("q0", relax.TensorStructInfo((heads, spatial, dim_head), "int8"))
    k0 = relax.Var("k0", relax.TensorStructInfo((heads, spatial, dim_head), "int8"))
    v0 = relax.Var("v0", relax.TensorStructInfo((heads, spatial, dim_head), "int8"))
    q1 = relax.Var("q1", relax.TensorStructInfo((heads, spatial, dim_head), "int8"))
    k1 = relax.Var("k1", relax.TensorStructInfo((heads, spatial, dim_head), "int8"))
    v1 = relax.Var("v1", relax.TensorStructInfo((heads, spatial, dim_head), "int8"))
    r00a = relax.Var("r00a", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r01a = relax.Var("r01a", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r10a = relax.Var("r10a", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r11a = relax.Var("r11a", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r00m = relax.Var("r00m", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r01m = relax.Var("r01m", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r10m = relax.Var("r10m", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r11m = relax.Var("r11m", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    wo0 = relax.Var("wo0", relax.TensorStructInfo((inner, c), "int8"))
    wo1 = relax.Var("wo1", relax.TensorStructInfo((inner, c), "int8"))
    params = [q0, k0, v0, q1, k1, v1, r00a, r01a, r10a, r11a, r00m, r01m, r10m, r11m, wo0, wo1]
    with bb.function("main", params):
        with bb.dataflow():
            s00 = _hmsa_pair_score_mixed(bb, q0, r00a, k0, dim_head)
            s01 = _hmsa_pair_score_mixed(bb, q0, r01a, k1, dim_head)
            s10 = _hmsa_pair_score_mixed(bb, q1, r10a, k0, dim_head)
            s11 = _hmsa_pair_score_mixed(bb, q1, r11a, k1, dim_head)
            w00, w01 = _softmax_two(bb, s00, s01)
            w10, w11 = _softmax_two(bb, s10, s11)
            msg00 = _hmsa_message_mixed(bb, v0, r00m)
            msg01 = _hmsa_message_mixed(bb, v1, r01m)
            msg10 = _hmsa_message_mixed(bb, v0, r10m)
            msg11 = _hmsa_message_mixed(bb, v1, r11m)
            out0 = _weighted_pair_sum(bb, w00, msg00, w01, msg01, heads, spatial)
            out1 = _weighted_pair_sum(bb, w10, msg10, w11, msg11, heads, spatial)
            y0 = _hmsa_project_out_mixed(bb, out0, wo0, plan)
            y1 = _hmsa_project_out_mixed(bb, out1, wo1, plan)
            y = bb.emit(relax.op.concat([y0, y1], axis=0))
            y = bb.emit(relax.op.reshape(y, (b, l, h, w, c)))
            gv = bb.emit_output(y)
        bb.emit_func_output(gv)
    return bb.finalize()


def build_relax_hmsa_static_2agent_fp16(plan: dict[str, Any]):
    from tvm import relax

    make_hmsa_static_2agent_param_plan(plan)
    b, l, h, w, c = plan["input_shape"]
    heads, dim_head, inner = plan["heads"], plan["dim_head"], plan["inner_dim"]
    spatial = plan["spatial_tokens"]
    bb = relax.BlockBuilder()
    x0 = relax.Var("x0", relax.TensorStructInfo((spatial, c), "float16"))
    x1 = relax.Var("x1", relax.TensorStructInfo((spatial, c), "float16"))
    q0w = relax.Var("q0w", relax.TensorStructInfo((c, inner), "float16"))
    k0w = relax.Var("k0w", relax.TensorStructInfo((c, inner), "float16"))
    v0w = relax.Var("v0w", relax.TensorStructInfo((c, inner), "float16"))
    q1w = relax.Var("q1w", relax.TensorStructInfo((c, inner), "float16"))
    k1w = relax.Var("k1w", relax.TensorStructInfo((c, inner), "float16"))
    v1w = relax.Var("v1w", relax.TensorStructInfo((c, inner), "float16"))
    r00a = relax.Var("r00a", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r01a = relax.Var("r01a", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r10a = relax.Var("r10a", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r11a = relax.Var("r11a", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r00m = relax.Var("r00m", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r01m = relax.Var("r01m", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r10m = relax.Var("r10m", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    r11m = relax.Var("r11m", relax.TensorStructInfo((heads, dim_head, dim_head), "float16"))
    wo0 = relax.Var("wo0", relax.TensorStructInfo((inner, c), "float16"))
    wo1 = relax.Var("wo1", relax.TensorStructInfo((inner, c), "float16"))
    params = [x0, x1, q0w, k0w, v0w, q1w, k1w, v1w, r00a, r01a, r10a, r11a, r00m, r01m, r10m, r11m, wo0, wo1]
    with bb.function("main", params):
        with bb.dataflow():
            q0, k0, v0 = _hmsa_project_qkv(bb, x0, q0w, k0w, v0w, plan)
            q1, k1, v1 = _hmsa_project_qkv(bb, x1, q1w, k1w, v1w, plan)
            y = _hmsa_emit_relation_body(
                bb, q0, k0, v0, q1, k1, v1,
                [r00a, r01a, r10a, r11a, r00m, r01m, r10m, r11m],
                [wo0, wo1],
                plan,
                mixed=False,
            )
            gv = bb.emit_output(y)
        bb.emit_func_output(gv)
    return bb.finalize()


def build_relax_hmsa_static_2agent_mixed_int8(plan: dict[str, Any]):
    from tvm import relax

    make_hmsa_static_2agent_param_plan(plan)
    b, l, h, w, c = plan["input_shape"]
    heads, dim_head, inner = plan["heads"], plan["dim_head"], plan["inner_dim"]
    spatial = plan["spatial_tokens"]
    bb = relax.BlockBuilder()
    x0 = relax.Var("x0", relax.TensorStructInfo((spatial, c), "int8"))
    x1 = relax.Var("x1", relax.TensorStructInfo((spatial, c), "int8"))
    q0w = relax.Var("q0w", relax.TensorStructInfo((c, inner), "int8"))
    k0w = relax.Var("k0w", relax.TensorStructInfo((c, inner), "int8"))
    v0w = relax.Var("v0w", relax.TensorStructInfo((c, inner), "int8"))
    q1w = relax.Var("q1w", relax.TensorStructInfo((c, inner), "int8"))
    k1w = relax.Var("k1w", relax.TensorStructInfo((c, inner), "int8"))
    v1w = relax.Var("v1w", relax.TensorStructInfo((c, inner), "int8"))
    r00a = relax.Var("r00a", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r01a = relax.Var("r01a", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r10a = relax.Var("r10a", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r11a = relax.Var("r11a", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r00m = relax.Var("r00m", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r01m = relax.Var("r01m", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r10m = relax.Var("r10m", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    r11m = relax.Var("r11m", relax.TensorStructInfo((heads, dim_head, dim_head), "int8"))
    wo0 = relax.Var("wo0", relax.TensorStructInfo((inner, c), "int8"))
    wo1 = relax.Var("wo1", relax.TensorStructInfo((inner, c), "int8"))
    params = [x0, x1, q0w, k0w, v0w, q1w, k1w, v1w, r00a, r01a, r10a, r11a, r00m, r01m, r10m, r11m, wo0, wo1]
    with bb.function("main", params):
        with bb.dataflow():
            q0, k0, v0 = _hmsa_project_qkv_mixed(bb, x0, q0w, k0w, v0w, plan)
            q1, k1, v1 = _hmsa_project_qkv_mixed(bb, x1, q1w, k1w, v1w, plan)
            y = _hmsa_emit_relation_body(
                bb, q0, k0, v0, q1, k1, v1,
                [r00a, r01a, r10a, r11a, r00m, r01m, r10m, r11m],
                [wo0, wo1],
                plan,
                mixed=True,
            )
            gv = bb.emit_output(y)
        bb.emit_func_output(gv)
    return bb.finalize()


def _bench_hmsa_variant(plan: dict[str, Any], variant: str, number: int, repeat: int, seed: int) -> dict[str, Any]:
    import tvm
    from tvm import relax

    dev = tvm.cuda(0)
    target = tvm.target.Target.from_device(dev)
    rng = np.random.default_rng(seed)
    stage = "build_relax"
    op = "hmsa_relation_core_explicit_2agent"
    try:
        if variant == "fp16":
            mod = build_relax_hmsa_relation_core_fp16(plan)
        else:
            mod = build_relax_hmsa_relation_core_mixed_int8(plan)
        stage = "compile_relax_tir"
        ex = compile_relax_module(mod, target)
        vm = relax.VirtualMachine(ex, dev)
        heads = plan["heads"]
        spatial = plan["spatial_tokens"]
        dim_head = plan["dim_head"]
        inner = plan["inner_dim"]
        c = plan["channels"]
        if variant == "fp16":
            arrays = [
                rng.standard_normal((heads, spatial, dim_head)).astype(np.float16)
                for _ in range(6)
            ]
            arrays.extend(
                rng.standard_normal((heads, dim_head, dim_head)).astype(np.float16)
                for _ in range(8)
            )
            arrays.extend([
                rng.standard_normal((inner, c)).astype(np.float16),
                rng.standard_normal((inner, c)).astype(np.float16),
            ])
        else:
            arrays = [
                rng.integers(-8, 8, size=(heads, spatial, dim_head), dtype=np.int8)
                for _ in range(6)
            ]
            arrays.extend(
                rng.integers(-8, 8, size=(heads, dim_head, dim_head), dtype=np.int8)
                for _ in range(8)
            )
            arrays.extend([
                rng.integers(-8, 8, size=(inner, c), dtype=np.int8),
                rng.integers(-8, 8, size=(inner, c), dtype=np.int8),
            ])
        tvm_args = [tvm.runtime.tensor(arr, device=dev) for arr in arrays]
        stage = "runtime_time_evaluator"
        timing = _time_vm(vm, tvm_args, dev, number, repeat)
        return _latency_entry(
            "OK",
            timing["p50_us"],
            mean_us=_round(timing["mean_us"], 3),
            min_us=_round(timing["min_us"], 3),
            p95_us=_round(timing["p95_us"], 3),
            precision=variant,
            stage=stage,
            op=op,
        )
    except Exception as exc:
        return make_tvm_blocked_entry(
            precision=variant,
            stage=stage,
            op=op,
            exc=exc,
            traceback_text=traceback.format_exc(),
        )


def _bench_hmsa_static_variant(plan: dict[str, Any], variant: str, number: int, repeat: int, seed: int) -> dict[str, Any]:
    import tvm
    from tvm import relax

    dev = tvm.cuda(0)
    target = tvm.target.Target.from_device(dev)
    rng = np.random.default_rng(seed)
    stage = "build_relax"
    op = "hmsa_static_2agent_qkv_relation_out"
    try:
        if variant == "fp16":
            mod = build_relax_hmsa_static_2agent_fp16(plan)
        else:
            mod = build_relax_hmsa_static_2agent_mixed_int8(plan)
        stage = "compile_relax_tir"
        ex = compile_relax_module(mod, target)
        vm = relax.VirtualMachine(ex, dev)
        spatial = plan["spatial_tokens"]
        c = plan["channels"]
        heads = plan["heads"]
        dim_head = plan["dim_head"]
        inner = plan["inner_dim"]
        if variant == "fp16":
            arrays = [
                rng.standard_normal((spatial, c)).astype(np.float16),
                rng.standard_normal((spatial, c)).astype(np.float16),
            ]
            arrays.extend(
                rng.standard_normal((c, inner)).astype(np.float16)
                for _ in range(6)
            )
            arrays.extend(
                rng.standard_normal((heads, dim_head, dim_head)).astype(np.float16)
                for _ in range(8)
            )
            arrays.extend([
                rng.standard_normal((inner, c)).astype(np.float16),
                rng.standard_normal((inner, c)).astype(np.float16),
            ])
        else:
            arrays = [
                rng.integers(-8, 8, size=(spatial, c), dtype=np.int8),
                rng.integers(-8, 8, size=(spatial, c), dtype=np.int8),
            ]
            arrays.extend(
                rng.integers(-8, 8, size=(c, inner), dtype=np.int8)
                for _ in range(6)
            )
            arrays.extend(
                rng.integers(-8, 8, size=(heads, dim_head, dim_head), dtype=np.int8)
                for _ in range(8)
            )
            arrays.extend([
                rng.integers(-8, 8, size=(inner, c), dtype=np.int8),
                rng.integers(-8, 8, size=(inner, c), dtype=np.int8),
            ])
        tvm_args = [tvm.runtime.tensor(arr, device=dev) for arr in arrays]
        stage = "runtime_time_evaluator"
        timing = _time_vm(vm, tvm_args, dev, number, repeat)
        return _latency_entry(
            "OK",
            timing["p50_us"],
            mean_us=_round(timing["mean_us"], 3),
            min_us=_round(timing["min_us"], 3),
            p95_us=_round(timing["p95_us"], 3),
            precision=variant,
            stage=stage,
            op=op,
        )
    except Exception as exc:
        return make_tvm_blocked_entry(
            precision=variant,
            stage=stage,
            op=op,
            exc=exc,
            traceback_text=traceback.format_exc(),
        )


def bench_hmsa_full_attention(
    plan: dict[str, Any],
    number: int,
    repeat: int,
    seed: int,
) -> dict[str, Any]:
    fp16 = _bench_hmsa_variant(plan, "fp16", number, repeat, seed)
    mixed = _bench_hmsa_variant(plan, "mixed_int8", number, repeat, seed)
    int8_alias = dict(mixed)
    int8_alias["quant_mode"] = "mixed_int8"
    return {
        "backend": "TVM",
        "scope": "full_attention_hmsa_relation_core_mixed_int8",
        "description": (
            "HMSA minimal explicit 2-agent relation core: q*relation_att*k, "
            "softmax over two agents, relation_msg*v, weighted aggregation, "
            "and per-type output projection."
        ),
        "shape_plan": plan,
        "prune_rate_pct": plan["prune_rate_pct"],
        "fp16": fp16,
        "mixed_int8": mixed,
        "int8": int8_alias,
        "caveat": (
            "This is a minimal explicit relation-core target. It fixes B=1,L=2 "
            "and explicit relation pair order; dynamic type dispatch and q/k/v "
            "input projection ModuleList lowering remain separate work."
        ),
    }


def bench_hmsa_static_2agent_attention(
    plan: dict[str, Any],
    number: int,
    repeat: int,
    seed: int,
) -> dict[str, Any]:
    fp16 = _bench_hmsa_static_variant(plan, "fp16", number, repeat, seed)
    mixed = _bench_hmsa_static_variant(plan, "mixed_int8", number, repeat, seed)
    int8_alias = dict(mixed)
    int8_alias["quant_mode"] = "mixed_int8"
    return {
        "backend": "TVM",
        "scope": "full_attention_hmsa_static_2agent_qkv_relation_core_mixed_int8",
        "description": (
            "HMSA static 2-agent type order [0,1]: q/k/v projections, explicit "
            "relation_att/msg core, softmax over two agents, aggregation, and "
            "per-type output projection."
        ),
        "shape_plan": plan,
        "static_param_plan": make_hmsa_static_2agent_param_plan(plan),
        "prune_rate_pct": plan["prune_rate_pct"],
        "fp16": fp16,
        "mixed_int8": mixed,
        "int8": int8_alias,
        "caveat": (
            "This target includes q/k/v/a projection for fixed type order [0,1]. "
            "Dynamic prior_encoding type dispatch and calibrated full-model e2e AP "
            "remain separate work."
        ),
    }


def _bench_mswin_variant(plan: dict[str, Any], variant: str, number: int, repeat: int, seed: int) -> dict[str, Any]:
    import tvm
    from tvm import relax

    dev = tvm.cuda(0)
    target = tvm.target.Target.from_device(dev)
    rng = np.random.default_rng(seed)
    stage = "build_relax"
    op = "mswin_bwa_window_qk_softmax_av_out"
    try:
        if variant == "fp16":
            mod = build_relax_mswin_bwa_fp16(plan)
        else:
            mod = build_relax_mswin_bwa_mixed_int8(plan)
        stage = "compile_relax_tir"
        ex = compile_relax_module(mod, target)
        vm = relax.VirtualMachine(ex, dev)
        b, l, h, w, c = plan["input_shape"]
        inner = plan["inner_dim"]
        tokens = plan["window_tokens"]
        if variant == "fp16":
            arrays = [
                rng.standard_normal((b, l, h, w, c)).astype(np.float16),
                rng.standard_normal((c, inner)).astype(np.float16),
                rng.standard_normal((c, inner)).astype(np.float16),
                rng.standard_normal((c, inner)).astype(np.float16),
                rng.standard_normal((inner, c)).astype(np.float16),
                rng.standard_normal((tokens, tokens)).astype(np.float16),
            ]
        else:
            arrays = [
                rng.integers(-16, 16, size=(b, l, h, w, c), dtype=np.int8),
                rng.integers(-16, 16, size=(c, inner), dtype=np.int8),
                rng.integers(-16, 16, size=(c, inner), dtype=np.int8),
                rng.integers(-16, 16, size=(c, inner), dtype=np.int8),
                rng.integers(-16, 16, size=(inner, c), dtype=np.int8),
                rng.standard_normal((tokens, tokens)).astype(np.float16),
            ]
        args = [tvm.runtime.tensor(arr, device=dev) for arr in arrays]
        stage = "runtime_time_evaluator"
        timing = _time_vm(vm, args, dev, number, repeat)
        return _latency_entry(
            "OK",
            timing["p50_us"],
            mean_us=_round(timing["mean_us"], 3),
            min_us=_round(timing["min_us"], 3),
            p95_us=_round(timing["p95_us"], 3),
            precision=variant,
            stage=stage,
            op=op,
        )
    except Exception as exc:
        return make_tvm_blocked_entry(
            precision=variant,
            stage=stage,
            op=op,
            exc=exc,
            traceback_text=traceback.format_exc(),
        )


def bench_mswin_full_attention(
    plan: dict[str, Any],
    number: int,
    repeat: int,
    seed: int,
) -> dict[str, Any]:
    fp16 = _bench_mswin_variant(plan, "fp16", number, repeat, seed)
    mixed = _bench_mswin_variant(plan, "mixed_int8", number, repeat, seed)
    int8_alias = dict(mixed)
    int8_alias["quant_mode"] = "mixed_int8"
    return {
        "backend": "TVM",
        "scope": "full_attention_mixed_int8",
        "description": "MSwin BaseWindowAttention full window Q/K/V projection, QK, relative-position add, softmax, AV, output projection.",
        "shape_plan": plan,
        "prune_rate_pct": plan["prune_rate_pct"],
        "fp16": fp16,
        "mixed_int8": mixed,
        "int8": int8_alias,
        "caveat": "mixed_int8 uses synthetic int8 casts/scales for TVM lowering evidence; it is not AP-calibrated.",
    }


def bench_matmul_pair(
    m: int,
    k: int,
    n: int,
    number: int,
    repeat: int,
    seed: int,
) -> dict[str, dict[str, Any]]:
    import tvm
    from tvm import relax

    dev = tvm.cuda(0)
    target = tvm.target.Target.from_device(dev)
    rng = np.random.default_rng(seed)
    result: dict[str, dict[str, Any]] = {}

    for dtype, out_dtype in (("float16", None), ("int8", "int32")):
        started = time.time()
        try:
            mod = build_relax_matmul(dtype, m, k, n, out_dtype)
            ex = compile_relax_module(mod, target)
            vm = relax.VirtualMachine(ex, dev)
            if dtype == "int8":
                x_np = rng.integers(-64, 64, size=(m, k), dtype=np.int8)
                w_np = rng.integers(-64, 64, size=(k, n), dtype=np.int8)
            else:
                x_np = rng.standard_normal((m, k)).astype(np.float16)
                w_np = rng.standard_normal((k, n)).astype(np.float16)
            args = [
                tvm.runtime.tensor(x_np, device=dev),
                tvm.runtime.tensor(w_np, device=dev),
            ]
            timing = _time_vm(vm, args, dev, number, repeat)
            key = "int8" if dtype == "int8" else "fp16"
            result[key] = _latency_entry(
                "OK",
                timing["p50_us"],
                mean_us=_round(timing["mean_us"], 3),
                min_us=_round(timing["min_us"], 3),
                p95_us=_round(timing["p95_us"], 3),
                compile_secs=_round(time.time() - started, 3),
                dtype=dtype,
                out_dtype=out_dtype or dtype,
            )
        except Exception as exc:
            key = "int8" if dtype == "int8" else "fp16"
            result[key] = {
                "status": "FAILED",
                "error": f"{type(exc).__name__}: {exc}",
                "traceback": traceback.format_exc()[-2000:],
                "dtype": dtype,
                "out_dtype": out_dtype or dtype,
            }
    return result


def make_blocked_full_attention(name: str, reason: str) -> dict[str, Any]:
    return {
        "backend": "TVM",
        "scope": "full_attention_int8_blocker",
        "description": name,
        "fp16": {
            "status": "SKIPPED",
            "reason": "T1-Q currently benchmarks direct TVM subops; full attention ONNX/Relax timing is separate.",
        },
        "int8": {
            "status": "BLOCKED",
            "reason": reason,
        },
    }


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-json", default="results/attention_axis_tvm_bench_v1.json")
    parser.add_argument("--batch", type=int, default=1)
    parser.add_argument("--agents", type=int, default=2)
    parser.add_argument("--h", type=int, default=64)
    parser.add_argument("--w", type=int, default=128)
    parser.add_argument("--channels", type=int, default=256)
    parser.add_argument("--number", type=int, default=20)
    parser.add_argument("--repeat", type=int, default=5)
    parser.add_argument("--seed", type=int, default=20260623)
    parser.add_argument("--full-attention", action="store_true")
    parser.add_argument("--full-only", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    import tvm

    m = int(args.batch * args.agents * args.h * args.w)
    c = int(args.channels)
    out = Path(args.out_json)
    out.parent.mkdir(parents=True, exist_ok=True)

    backend_results: dict[str, dict[str, Any]] = {}
    specs = {
        "linear_256x256_direct": {
            "shape": (m, c, c),
            "description": "HMSA q/k/v/a projection direct matmul, 256->256",
            "prune_rate_pct": 0,
            "prune_axis": "none",
        },
        "linear_qkv_direct": {
            "shape": (m, c, c * 3),
            "description": "MSwin QKV projection direct matmul, 256->768",
            "prune_rate_pct": 0,
            "prune_axis": "none",
        },
        "mswin_out_direct": {
            "shape": (m, c, c),
            "description": "MSwin output projection direct matmul, 256->256",
            "prune_rate_pct": 0,
            "prune_axis": "none",
        },
        "hmsa_proj_head_p50_direct": {
            "shape": (m, c, c // 2),
            "description": "HMSA q/k/v head-pruned p50 projection direct matmul, 256->128",
            "prune_rate_pct": 50,
            "prune_axis": "hmsa_head",
            "baseline_target": "linear_256x256_direct",
        },
        "hmsa_out_head_p50_direct": {
            "shape": (m, c // 2, c),
            "description": "HMSA head-pruned p50 output projection direct matmul, 128->256",
            "prune_rate_pct": 50,
            "prune_axis": "hmsa_head",
            "baseline_target": "linear_256x256_direct",
        },
        "mswin_qkv_head_p50_direct": {
            "shape": (m, c, (c // 2) * 3),
            "description": "MSwin p50 head-pruned QKV direct matmul, 256->384",
            "prune_rate_pct": 50,
            "prune_axis": "mswin_head",
            "baseline_target": "linear_qkv_direct",
        },
        "mswin_out_head_p50_direct": {
            "shape": (m, c // 2, c),
            "description": "MSwin p50 head-pruned output projection direct matmul, 128->256",
            "prune_rate_pct": 50,
            "prune_axis": "mswin_head",
            "baseline_target": "mswin_out_direct",
        },
    }
    if not args.full_only:
        for name, spec in specs.items():
            bm = bench_matmul_pair(*spec["shape"], args.number, args.repeat, args.seed)
            backend_results[name] = {
                "backend": "TVM",
                "scope": "direct_matmul",
                "description": spec["description"],
                "shape_mkn": list(spec["shape"]),
                "prune_rate_pct": spec["prune_rate_pct"],
                "prune_axis": spec["prune_axis"],
                "baseline_target": spec.get("baseline_target"),
                **bm,
            }

        backend_results["ffn_direct_pair_estimate"] = {
            "backend": "TVM",
            "scope": "direct_matmul_pair_estimate",
            "description": "FeedForward Linear-GELU-Linear estimated from two 256->256 matmuls; GELU/requant not included.",
            "shape_mkn": [m, c, c],
            "fp16": dict(backend_results["linear_256x256_direct"]["fp16"]),
            "int8": dict(backend_results["linear_256x256_direct"]["int8"]),
        }
        for precision in ("fp16", "int8"):
            item = backend_results["ffn_direct_pair_estimate"][precision]
            if item.get("status") == "OK":
                for key in ("p50_ms", "p50_us", "mean_us", "min_us", "p95_us"):
                    if key in item and item[key] is not None:
                        item[key] = _round(float(item[key]) * 2.0, 6 if key.endswith("_ms") else 3)
                item["estimate_multiplier"] = 2

    if args.full_attention:
        full_plan = make_mswin_bwa_shape_plan(
            args.batch, args.agents, args.h, args.w, args.channels,
            heads=4, dim_head=64, window_size=16, prune_rate_pct=0,
        )
        backend_results["mswin_bwa_full_attention"] = bench_mswin_full_attention(
            full_plan, args.number, args.repeat, args.seed,
        )
        p50_plan = make_mswin_bwa_shape_plan(
            args.batch, args.agents, args.h, args.w, args.channels,
            heads=2, dim_head=64, window_size=16, prune_rate_pct=50,
        )
        backend_results["mswin_bwa_p50_full_attention"] = bench_mswin_full_attention(
            p50_plan, args.number, args.repeat, args.seed,
        )
        hmsa_plan = make_hmsa_shape_plan(
            args.batch, args.agents, args.h, args.w, args.channels,
            heads=8, dim_head=32, num_types=2, num_relations=4, prune_rate_pct=0,
        )
        backend_results["hmsa_full_attention"] = bench_hmsa_static_2agent_attention(
            hmsa_plan, args.number, args.repeat, args.seed,
        )
        hmsa_p50_plan = make_hmsa_shape_plan(
            args.batch, args.agents, args.h, args.w, args.channels,
            heads=4, dim_head=32, num_types=2, num_relations=4, prune_rate_pct=50,
        )
        backend_results["hmsa_p50_full_attention"] = bench_hmsa_static_2agent_attention(
            hmsa_p50_plan, args.number, args.repeat, args.seed,
        )

    if "mswin_bwa_full_attention" not in backend_results:
        backend_results["mswin_bwa_full_attention"] = make_blocked_full_attention(
            "BaseWindowAttention full qkv/einsum/softmax/out",
            "Run with --full-attention to attempt full TVM FP16/mixed INT8 attention lowering.",
        )
    if "hmsa_full_attention" not in backend_results:
        hmsa_plan = make_hmsa_shape_plan(
            args.batch, args.agents, args.h, args.w, args.channels,
            heads=8, dim_head=32, num_types=2, num_relations=4, prune_rate_pct=0,
        )
        backend_results["hmsa_full_attention"] = {
            "backend": "TVM",
            "scope": "full_attention_hmsa_relation_core_mixed_int8",
            "description": "HGTCavAttention minimal explicit relation core",
            "shape_plan": hmsa_plan,
            "fp16": make_hmsa_not_implemented_entry(hmsa_plan, "fp16"),
            "mixed_int8": make_hmsa_not_implemented_entry(hmsa_plan, "mixed_int8"),
            "int8": make_hmsa_not_implemented_entry(hmsa_plan, "mixed_int8"),
        }

    report = {
        "phase": "T1-Q-TVM",
        "backend": "TVM",
        "tvm_version": tvm.__version__,
        "device": str(tvm.cuda(0)),
        "input_shape": [args.batch, args.agents, args.h, args.w, args.channels],
        "matmul_m": m,
        "number": args.number,
        "repeat": args.repeat,
        "backend_results": backend_results,
        "caveat": (
            "Direct INT8 subops use TVM Relax int8 matmul, not QDQ-ONNX and not non-TVM engines. "
            "Full-attention entries use synthetic mixed INT8 for runtime evidence; MSwin covers the "
            "full window attention target, while HMSA covers a static 2-agent [0,1] q/k/v projection, "
            "relation core, and output projection target until dynamic type dispatch and calibrated "
            "full-model e2e AP are added."
        ),
    }
    out.write_text(json.dumps(report, indent=2, ensure_ascii=False))
    print(json.dumps(report, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
